// src/components/Frameworks.jsx
import React from 'react';
import Icon from './Icon';
import { toInstall } from '../utils';

const Frameworks = ({frameworks, visible}) => {

  return (
    <div className="section is-x">
      <div className="container">
        <h2 className="title">Frameworks</h2>
        <table className="table has-text-centered is-striped is-bordered">
          <thead>
          <tr>
            <th className="is-first"/>
            {frameworks
              .filter(framework => visible.has(framework.slug))
              .map(framework => {
              return (
                <th key={framework.slug}>
                  <span data-title={framework.description} className="tag is-tooltip is-info">{framework.name}</span>
                </th>
              );
            })}
          </tr>
          </thead>
          <tbody>
          <tr>
            <td><strong>Links</strong></td>
            {frameworks
              .filter(framework => visible.has(framework.slug))
              .map(framework => {
              return (
                <td key={framework.slug}>
                  <div className="field has-addons has-text-centered">
                    <div className="control">
                      <a href={framework.url} target="_blank" rel="noopener noreferrer"
                         className="button is-small is-info is-outlined">
                        <Icon name="globe"/>
                        <span className="button-text">Website</span>
                      </a>
                    </div>
                    <div className="control">
                      <a href={framework.documentation} target="_blank" rel="noopener noreferrer"
                         className="button is-small is-info is-outlined">
                        <Icon name="book"/>
                        <span className="button-text">Docs</span>
                      </a>
                    </div>
                    <div className="control">
                      <a className="button is-small is-info is-outlined" href={framework.github} target="_blank"
                         rel="noopener noreferrer">
                        <Icon name="github"/>
                        <span className="button-text">GitHub</span>
                      </a>
                    </div>
                  </div>
                </td>
              );
            })}
          </tr>
          <tr>
            <td><strong>How To Install?</strong></td>
            {frameworks
              .filter(framework => visible.has(framework.slug))
              .map(framework => {
              return (
                <td className="no-padding" key={framework.slug}>
                  <pre><code>bower i -S {toInstall(framework, 'bower')}</code></pre>
                  <pre><code>npm i -S {toInstall(framework, 'npm')}</code></pre>
                  <pre><code>yarn add {toInstall(framework, 'yarn')}</code></pre>
                </td>
              );
            })}
          </tr>
          <tr>
            <td><strong>Github Stats</strong></td>
            {frameworks
              .filter(framework => visible.has(framework.slug))
              .map(framework => {
              return (
                <td key={framework.slug}>
                  <span className="tag is-small is-dark"><Icon name="code-fork"/>{framework.stats.forks}</span>
                  <span className="tag is-small is-dark"><Icon name="star"/>{framework.stats.stars}</span>
                </td>
              );
            })}
          </tr>
          <tr>
            <td><strong>Latest Version</strong></td>
            {frameworks
              .filter(framework => visible.has(framework.slug))
              .map(framework => {
              return (
                <td key={framework.slug}>
                  <a target="_blank" rel="noopener noreferrer" href={`${framework.github}/releases`}
                     className="tag is-small is-info"><Icon name="history"/><span>v{framework.version}</span></a>
                </td>
              );
            })}
          </tr>
          <tr>
            <td><strong>Icons</strong></td>
            {frameworks
              .filter(framework => visible.has(framework.slug))
              .map(framework => {
              return (
                <td key={framework.slug}>
                  {framework.icons && <a data-title={framework.icons.name} target="_blank" rel="noopener noreferrer" className="tag is-tooltip is-small is-success" href={framework.icons.url}>Yes</a>}
                  {!framework.icons && <span className="tag is-small is-danger">No</span>}
                </td>
              );
            })}
          </tr>
          <tr>
            <td><strong>CSS Preprocessor</strong></td>
            {frameworks
              .filter(framework => visible.has(framework.slug))
              .map(framework => {
              return (
                <td key={framework.slug}>
                  <span className="tag is-small is-info">{framework.css}</span>
                </td>
              );
            })}
          </tr>
          <tr>
            <td><strong>JS Library?</strong></td>
            {frameworks
              .filter(framework => visible.has(framework.slug))
              .map(framework => {
              return (
                <td key={framework.slug}>
                  {framework.js &&
                  <a target="_blank" rel="noopener noreferrer" className="tag is-small is-success" href={framework.js}>Yes</a>}
                  {!framework.js && <span className="tag is-small is-danger">No</span>}
                </td>
              );
            })}
          </tr>
          <tr>
            <td><strong>License</strong></td>
            {frameworks
              .filter(framework => visible.has(framework.slug))
              .map(framework => {
              return (
                <td key={framework.slug}>
                  {framework.licence && <a target="_blank" rel="noopener noreferrer" className="tag is-small is-info"
                                           href={framework.licence.url}>{framework.licence.name}</a>}
                  {!framework.licence &&
                  <a target="_blank" rel="noopener noreferrer" href="https://opensource.org/licenses/MIT"
                     className="tag is-small is-info">MIT</a>}
                </td>
              );
            })}
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default Frameworks;

// src/components/Frameworks.vue
<template>
    <div class="section">
        <div class="container is-x">
            <h2 id="frameworks" class="title">Frameworks</h2>
            <div :class="{ 'is-hidden': ready }" class="notification">
                Loading ...
            </div>
            <table :class="{ 'is-hidden': !ready }" class="table has-text-centered is-striped is-bordered">
                <thead>
                <tr>
                    <th><strong>Details</strong></th>
                    <th v-for="framework in content.frameworks"><span class="tag is-info">{{ framework.name }}</span>
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><strong>Links</strong></td>
                    <td v-for="framework in content.frameworks">
                        <div class="control has-addons">
                            <a class="button is-small is-info is-outlined" :href="framework.url" target="_blank">
                                  <span class="icon is-small">
                                    <i class="fa fa-globe"></i>
                                  </span>
                                <span>Website</span>
                            </a>
                            <a class="button is-small is-info is-outlined" :href="framework.documentation"
                               target="_blank">
                              <span class="icon is-small">
                                <i class="fa fa-book"></i>
                              </span>
                                <span>Docs</span>
                            </a>
                            <a class="button is-small is-info is-outlined" :href="framework.github" target="_blank">
                              <span class="icon is-small">
                                <i class="fa fa-github"></i>
                              </span>
                                <span>GitHub</span>
                            </a>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><strong>Description</strong></td>
                    <td v-for="framework in content.frameworks">
                        <p>{{ framework.description }}</p>
                    </td>
                </tr>
                <tr>
                    <td><strong>Install</strong></td>
                    <td class="no-padding" v-for="framework in content.frameworks">
                        <pre><code>bower install {{ framework.install ? framework.install : framework.slug }}</code></pre>
                        <pre><code>npm install {{ framework.install ? framework.install : framework.slug }}</code></pre>
                        <pre><code>yarn add {{ framework.install ? framework.install : framework.slug }}</code></pre>
                    </td>
                </tr>
                <tr>
                    <td><strong>Stats</strong></td>
                    <td v-for="framework in content.frameworks">
                        <span class="tag is-small is-dark"><i class="fa fa-code-fork"></i>&nbsp;{{ framework.stats.forks }}</span>
                        <span class="tag is-small is-dark"><i
                                class="fa fa-star"></i>&nbsp;{{ framework.stats.stars }}</span>
                    </td>
                </tr>
                <tr>
                    <td><strong>Browsers</strong></td>
                    <td v-for="framework in content.frameworks">
                        <i class="fa fa-chrome"></i>
                        <i class="fa fa-safari"></i>
                        <i class="fa fa-firefox"></i>
                        <i class="fa fa-opera"></i>
                        <i class="fa fa-internet-explorer"></i>
                    </td>
                </tr>
                <tr>
                    <td><strong>Icons</strong></td>
                    <td v-for="framework in content.frameworks">
                        <a target="_blank" :href="framework.icons.url" class="tag is-small is-info">{{
                            framework.icons.name }}</a>
                    </td>
                </tr>
                <tr>
                    <td><strong>CSS</strong></td>
                    <td v-for="framework in content.frameworks">
                        <span class="tag is-small is-info">{{ framework.css }}</span>
                    </td>
                </tr>
                <tr>
                    <td><strong>JS Library</strong></td>
                    <td v-for="framework in content.frameworks">
                        <!--<a v-if="framework.js" class="button is-small is-info is-outlined" :href="framework.js"-->
                        <!--target="_blank">-->
                        <!--<span class="icon is-small">-->
                        <!--<i class="fa fa-eye"></i>-->
                        <!--</span>-->
                        <!--<span>Demo</span>-->
                        <!--</a>-->
                        <span v-if="framework.js">
                            <a target="_blank" :href="framework.js" class="tag is-small is-success">Yes</a>
                        </span>
                        <span v-else class="tag is-small is-danger">No</span>
                    </td>
                </tr>
                <tr>
                    <td><strong>License</strong></td>
                    <td v-for="framework in content.frameworks">
                        <a target="_blank" href="https://opensource.org/licenses/MIT"
                           class="tag is-small is-info">MIT</a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</template>
<script>
    export default {
        props: ['ready', 'content']
    }





</script>
